import { bus } from './eventbus.js';
import {
  destroyPlyr,
  resetMediaEl,
  hideAllMedia,
  showPreviewError,
  setFitBtnVisible,
  updateFitBtnFromVideo,
  setTracks,
  getActivePlyr,
  applyPlyr,
  switchToTranscodeSource,
  setupErrorHandler,
  getActiveMedia,
  saveProgress,
  hasResumeCandidate,
  restorePlaybackTime,
  setupAudioTrackHandling,
  resumeLast,
  bindGlobalHotkeys,
  playItem,
} from './player/index.js';

export {
  destroyPlyr,
  resetMediaEl,
  hideAllMedia,
  showPreviewError,
  setFitBtnVisible,
  updateFitBtnFromVideo,
  setTracks,
  getActivePlyr,
  applyPlyr,
  switchToTranscodeSource,
  setupErrorHandler,
  getActiveMedia,
  saveProgress,
  hasResumeCandidate,
  restorePlaybackTime,
  setupAudioTrackHandling,
  resumeLast,
  bindGlobalHotkeys,
  playItem,
};

bus.on('play:request', (item, opts) => playItem(item, opts));
